# Generated by Django 4.0.6 on 2022-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=40)),
                ('des', models.TextField()),
                ('phone', models.IntegerField(default='', max_length=11)),
            ],
        ),
    ]
